supabase_key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Y2d4cmRyYWNta3B2ZmJxY2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTg2MDU1MTIsImV4cCI6MjAzNDE4MTUxMn0._HRBDDoLpe-sS45LSIcaRxn6KKExD5qcWz5U_zO9JKY'
supabase_url = 'https://jzcgxrdracmkpvfbqchc.supabase.co'
